# Generated by Django 4.2.23 on 2025-06-23 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fitness_type', models.CharField(choices=[('zumba', 'Zumba'), ('yoga', 'Yoga'), ('hiit', 'HIIT')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(max_length=50)),
                ('total_slots', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_slots', models.PositiveIntegerField()),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.fitness_class')),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
